### ISSUE TITLE
Factory problems

### ISSUE THREAD

**Issue by peterbe** [alexmingoia/gulp-jsx#9]
```
:~/dev/JAVASCRIPT/activity (master *)$ gulp build
[11:44:04] Using gulpfile ~/dev/JAVASCRIPT/activity/gulpfile.js
[11:44:04] Starting 'build'...

/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp-jsx/node_modules/jsx-transform/lib/jsx.js:92
    throw new Error('Missing options.factory function name.');
          ^
Error: Missing options.factory function name.
    at processOptions (/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp-jsx/node_modules/jsx-transform/lib/jsx.js:92:11)
    at Object.fromString (/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp-jsx/node_modules/jsx-transform/lib/jsx.js:68:13)
    at DestroyableTransform.write [as _transform] (/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp-jsx/lib/jsx.js:29:15)
    at DestroyableTransform.Transform._read (/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp-jsx/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp-jsx/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp-jsx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp-jsx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp-jsx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/peterbe/dev/JAVASCRIPT/activity/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
:~/dev/JAVASCRIPT/activity (master *)$
```
I debugged line 92 in jsx.js and the `options` variable is `{}` so the `options.factory` is `undefined`. 

My gulp file looks like this:
```
var gulp = require('gulp');
var serve = require('gulp-serve');
var jsx = require('gulp-jsx');

gulp.task('serve', serve('.'));

gulp.task('build', function() {
  return gulp.src('src/*.js')
    .pipe(jsx())
    .pipe(gulp.dest('dist'));
});

gulp.task('default', function() {
  // place code for your default task here
});
```

Wouldn't be surprised if it's something obvious.

**Comment by peterbe** [comment]
For what it's worth, I only have 1 file. `src/app.js` and it looks like this:
```
/** @jsx React.DOM */
var FilteredList = React.createClass({
...
```

**Comment by fkwd** [comment]
I confirm the problem. Someone knows a solution ?

**Comment by loveLibra** [comment]
the same problem

**Comment by markwylde** [comment]
+1

**Comment by alexmingoia** [comment]
You're missing the [`factory`](https://github.com/alexmingoia/jsx-transform#jsx-transformfromstringstr-options--string) option:

```javascript:
gulp.task('build', function() {
  return gulp.src('src/*.js')
    .pipe(jsx({
      factory: "React.createElement"
    }))
    .pipe(gulp.dest('dist'));
});
```

**Comment by tcarlsen** [comment]
@alexmingoia I think you should but that in the example in the README. I ran into the same issue
